stages:
  - deploy

admin-deploy:
  stage: deploy
  only:
   - master
  script:
    - cd /home/sergio_rivas/vapehouse/admin
    - sudo npm run build
    - sudo rm -r /var/www/html/admin-build/*
    - sudo cp -r build/* /var/www/html/admin-build
    - echo "Despliegue Admin completo!"

shop-deploy:
  stage: deploy
  only:
    - master
  script:
    - cd /home/sergio_rivas/vapehouse/shop
    - sudo yarn build
    - sudo rm -r /var/www/html/shop-build/*
    - sudo cp -r build/* /var/www/html/shop-build
    - echo "Despliegue Shop completo!"