stages:
  - deploy-admin
  - deploy-shop
  # - deploy-backend

# deploy-backend:
#   stage: deploy-backend
#   only:
#     - master
#   script:
#     - cd backend
#     - CI=false mvn clean package
#     - cd target
#     - CI=false java -jar backend-0.0.1-SNAPSHOT.jar & > /dev/null

admin-deploy:
  stage: deploy-admin
  only:
   - master
  script:
    - cd admin
    - CI=false npm install
    - CI=false npm run build
    - rm -r /var/www/html/admin-build/*
    - cp -r build/* /var/www/html/admin-build
    - echo "Despliegue Admin completo !"

shop-deploy:
  stage: deploy-shop
  only:
    - master
  script:
    - cd shop
    - CI=false npm install
    - CI=false npm run build
    - rm -r /var/www/html/shop-build/*
    - cp -r build/* /var/www/html/shop-build
    - echo "Despliegue Shop completo !"