stages:
  - deploy-backend
  - deploy-admin
  - deploy-shop

deploy-backend:
  stage: deploy-backend
  only:
    - master
  script:
    - cd backend
    - CI=false mvn clean package
    - cd target
    - java -jar backend-0.0.1-SNAPSHOT.jar &

admin-deploy:
  stage: deploy-admin
  only:
   - master
  script:
    - cd admin
    - CI=false npm install
    - CI=false npm run build
    - rm -r /var/www/html/admin-build/*
    - cp -r build/* /var/www/html/admin-build
    - echo "Despliegue Admin completo !"

shop-deploy:
  stage: deploy-shop
  only:
    - master
  script:
    - cd shop
    - npm run build
    - rm -r /var/www/html/shop-build/*
    - cp -r build/* /var/www/html/shop-build
    - echo "Despliegue Shop completo !"